version: "3.8"

services:
  web:
    image: IMAGE_PLACEHOLDER

    ports:
      - "8888:80"

    deploy:
      replicas: 2

      placement:
        preferences:
          - spread: node.id

      restart_policy:
        condition: on-failure

      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

    networks:
      - app-network

networks:
  app-network:
    driver: overlay